### ISSUE TITLE
Simulator debug output spams lots of Open logfile lines when sensor logging enabled

### ISSUE THREAD

**Issue by agibson2** [FrSkyRC/ETHOS-Feedback-Community#1192]
Ethos 1.1.0 alpha 6  (haven't tested 7 yet)

If you enable logging to csv for sensor data on a model in the simulator, The debug console (if you launch simulator.exe from a cmd window in Windows) shows a bunch of Open logfile ... with changing filenames. I checked and it is only writing to one logfile so I am puzzled why it would log that it is opening other files with different timestamps in the logfile name. Nothing breaks because of it that I am aware of. It is just annoying spamming the console. I have logging set to 5 times a second on the transmitter which coincides with the log.

...
518134 Open logfile /logs/Solar-2021-12-07-22-45-46.csv
518423 Open logfile /logs/Solar-2021-12-07-22-45-46.csv
518631 Open logfile /logs/Solar-2021-12-07-22-45-46.csv
518919 Open logfile /logs/Solar-2021-12-07-22-45-46.csv
519127 Open logfile /logs/Solar-2021-12-07-22-45-46.csv
519495 Open logfile /logs/Solar-2021-12-07-22-45-47.csv
519782 Open logfile /logs/Solar-2021-12-07-22-45-47.csv
519990 Open logfile /logs/Solar-2021-12-07-22-45-47.csv
520279 Open logfile /logs/Solar-2021-12-07-22-45-47.csv
520487 Open logfile /logs/Solar-2021-12-07-22-45-47.csv
520839 Open logfile /logs/Solar-2021-12-07-22-45-48.csv
521062 Open logfile /logs/Solar-2021-12-07-22-45-48.csv
521350 Open logfile /logs/Solar-2021-12-07-22-45-48.csv
521558 Open logfile /logs/Solar-2021-12-07-22-45-48.csv
521847 Open logfile /logs/Solar-2021-12-07-22-45-49.csv
522134 Open logfile /logs/Solar-2021-12-07-22-45-49.csv
522422 Open logfile /logs/Solar-2021-12-07-22-45-49.csv
522630 Open logfile /logs/Solar-2021-12-07-22-45-49.csv
522918 Open logfile /logs/Solar-2021-12-07-22-45-49.csv
523206 Open logfile /logs/Solar-2021-12-07-22-45-50.csv

As you can see from the screenshot, It is only writing to one file like it should for the starting of simulator. 

![EthosLogDirectoryOnWindows](https://user-images.githubusercontent.com/6733850/145261745-db59df8d-1e8f-4d01-b400-ccf4064f2653.png)

**Comment by bsongis-frsky** [comment]
Fixed in alpha7 but I won't release a simulator for this alpha release, you will have to wait for next one

**Comment by agibson2** [comment]
Still an issue in alpha 8...

048234 Open logfile /logs/Solar-2021-12-09-20-17-30.csv
048661 Open logfile /logs/Solar-2021-12-09-20-17-30.csv
048885 Open logfile /logs/Solar-2021-12-09-20-17-30.csv
049174 Open logfile /logs/Solar-2021-12-09-20-17-30.csv
049382 Open logfile /logs/Solar-2021-12-09-20-17-30.csv
049734 Open logfile /logs/Solar-2021-12-09-20-17-31.csv
049942 Open logfile /logs/Solar-2021-12-09-20-17-31.csv
050230 Open logfile /logs/Solar-2021-12-09-20-17-31.csv
050438 Open logfile /logs/Solar-2021-12-09-20-17-31.csv
050726 Open logfile /logs/Solar-2021-12-09-20-17-31.csv
051095 Open logfile /logs/Solar-2021-12-09-20-17-32.csv
051303 Open logfile /logs/Solar-2021-12-09-20-17-32.csv
051511 Open logfile /logs/Solar-2021-12-09-20-17-32.csv
051799 Open logfile /logs/Solar-2021-12-09-20-17-32.csv
052007 Open logfile /logs/Solar-2021-12-09-20-17-33.csv
052382 Open logfile /logs/Solar-2021-12-09-20-17-33.csv
052670 Open logfile /logs/Solar-2021-12-09-20-17-33.csv
052878 Open logfile /logs/Solar-2021-12-09-20-17-33.csv

**Comment by agibson2** [comment]
This should be reopened.  It is still an issue in alpha 12
