### ISSUE TITLE
Emergency Mode

### ISSUE THREAD

**Issue by piocarlos** [FrSkyRC/ETHOS-Feedback-Community#1293]
Hello, I am on 1.0.17 and sometimes when I change to a different model my X20s still goes into Emergency Mode. I have updated my SD Card to a 32gb.

**Comment by bsongis-frsky** [comment]
do you use flight modes?

**Comment by piocarlos** [comment]
no ,dont ever use flight modes.

**Comment by EngelMT** [comment]
Today we got the info from a customer who got Emergency Mode with 1.0.17 too. In his case, it was when he wanted to tie a receiver.

**Comment by EngelMT** [comment]
After flashing my own radio to TD Firmware 2.1.15 my radio goes to Emergency mode if I will change a plane or when I will reset the timer viy switch. Can be that other actions can thus lead to an emergency mode. I have not tried anything else yet.

**Comment by EngelMT** [comment]
Flashed back to TD 2.1.14. But the same. Emergency Mode every time if I reset the timer or if I will change a model.

**Comment by bsongis-frsky** [comment]
It makes no sense, I need your SD to understand!

**Comment by dudley1943** [comment]
I have had several incidents when my X20s went into EMERGENCY MODE when changing models (from one plane to another plane).  This does not occur with every plague change BUT does with the same plane once it happens. I have to turnoff the transmitter ad restart it.  I turns on okay but is always bact to the plane I had been on previously.  No matter how many times I attempt to change to the plane I had unsuccessfully attempted to select it will always immediately go into emergency mode.  I can successfully turn off and then turn back on the transmitter and change to any of the other 12 or so other planes and all is well.  However if I again attempt to change to the same plane that would experienced the emergency mode, it will again immediately enter emergency mode.  I am forced to shut down the radio and turn it back on and delete that plane.  Any ideas?

**Comment by EngelMT** [comment]
@dudley1943 First I think you have to flash to a new ETHOS version. Your problem could be solved with 1.0.14 or later.

**Comment by bsongis-frsky** [comment]
I have found the issue. It has been solved in 1.1.0 alphas long time ago and the fix had not been ported to 1.0 since, my mistake!

**Comment by bsongis-frsky** [comment]
Will be fixed in next 1.0 release which should come before the end of the week

**Comment by dudley1943** [comment]
Thank you for your response.  Can you advise if the fix will be updated to the public?

Sent from my iPad

On Jan 13, 2022, at 6:25 AM, Bertrand Songis @ FrSky ***@***.***> wrote:

﻿
I have found the issue. It has been solved in 1.1.0 alphas long time ago and the fix had not been ported to 1.0 since, my mistake!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dudley1943** [comment]
Thank you for the update.

Sent from my iPad

On Jan 13, 2022, at 6:26 AM, Bertrand Songis @ FrSky ***@***.***> wrote:

﻿
Will be fixed in next 1.0 release which should come before the end of the week

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EngelMT** [comment]
> I have found the issue. It has been solved in 1.1.0 alphas long time ago and the fix had not been ported to 1.0 since, my mistake!

@bsongis-frsky 

Hi Bertrand, I assume that you forgot the bug fix in 1.0.16, 1.0.17 and 18 as well, right? Because most of the reports about the problem came with these versions. So you would have to fix it again in the next release of these versions.
