### ISSUE TITLE
No automatic reconnection PARA

### ISSUE THREAD

**Issue by EngelMT** [FrSkyRC/ETHOS-Feedback-Community#1583]
A customer claimed the following.

He paired his DIY BT headtracker (with Para-Bluetooth BT32) with the X20S in master status and everything works fine so far. However, after each transmitter switch-off and restart, the BT connection must be searched for and activated again via the wireless menu.

The menu item >Record previous connection< does not work either - only a new search with corresponding selection and confirmation works (reliably).

Actually, I know that after successful pairing of the two BT devices, the connection is remembered and immediately re-established after a restart, as long as no new, different connection is requested...

This is exactly how it works in combination with my old Futaba FF10 and retrofitted Para-BT module!

**Comment by phHed** [comment]
This is also the case when using the master / student buddy box system. Reconnection is not automatic and the new device discovery step has to be repeated.

**Comment by Hobby4life** [comment]
I can confirm too. No reconnect trainer

**Comment by jasc76** [comment]
Still not working (1.4.4)
Headtracker as Trainer (slave) Input

**Comment by riga23** [comment]
I can confirm too. No automatic reconnect trainer after turn off and turn on the radio (X20S Master & X18S Slave) 1.4.8 togheter

**Comment by yak-54** [comment]
same here X12S trainer and head tracker

**Comment by jasc76** [comment]
I can confirm that. Always have to search first, can’t just click reconnect

**Comment by Ze-baloo** [comment]
Same issue on my side, X18 as master tx and X9d 2019 as slave tx.
I always need to start a new bluetooth device search when using the trainer mode.

Other point it lists only the bluetooth adress of the devices available nearby, if you have many bluetooth devices around, finding the right one becomes more complicated.

The adress and the device type should be shown on the list.

;-)

**Comment by arshish1612** [comment]
Ive faced this issue too for trainer mode

**Comment by bsongis-frsky** [comment]
It is fixed in Ethos 1.7.0 now
It needs the new Bluetooth firmware

**Comment by secretman28** [comment]
how i update? 
im with the nightly 26.1 and i mess so mutch on doing a trainer bluetooth head tracker to find its not the code that dont work its i need to update the bluetooth...
where i find this ?

**Comment by pgaryga** [comment]
Still a problem with Ethos 26.1.0 and Bluetooth firmware 26.0.10 on X18RS and Headtracker using Bluetooth.
