### ISSUE TITLE
TD R10 issue

### ISSUE THREAD

**Issue by Mury123** [FrSkyRC/ETHOS-Feedback-Community#2008]
Using TDR10 getting incorrect min/max Rx batt voltage readings in flight data recorder function. Reading 16.544v instead of 6.0v as indicated on usual Rx batt telemetry function. X20s 1.4.1 EU, TD isrm 2.2.2 EULBT.

**Comment by Mury123** [comment]
Hi, yes TD-ISRM module is on 2.2.2 (EU-LBT).

Sent from Sky Yahoo Mail on Android 
 
  On Mon, 24 Oct 2022 at 4:50 pm, Bertrand Songis @ ***@***.***> wrote:   


I have heard about this issue, it is not in Ethos and I thought it had been fixed some time ago, is your module firmware up to date?

**Comment by xet303** [comment]
Idem here with 1.4.1 FCC----ISRM 2.2.2 FCC----TDR10 HW:1.1.0 FW: 1.0.7
Included files below.
[from TD R10 blackbox file.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9854127/from.TD.R10.blackbox.file.csv)
[from special fonction telemetry reccorded.csv](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/9854132/from.special.fonction.telemetry.reccorded.csv)

Thanks

**Comment by pld74** [comment]
I initially found this bug and I havent seen any new RX FW to fix this issue. 

https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1892

**Comment by Mury123** [comment]
I have a clubmate with an X20s and new TDR10 receiver, all up to date EU LBT etc. The  same issue is seen, telemetry Rx voltage 6.1v but flight data shows 15.4v. Looks like this is not an isolated problem. Is there any more information required?

**Comment by Mury123** [comment]
This issue has still not been solved so should not receive a stale label. It is a definite fault reported and repeatable by a number of users but for some reason has not been investigated.

**Comment by janekx** [comment]
Still present i push on FrSky to look on it

**Comment by Mury123** [comment]
I think it's clearly a TD r10 receiver issue but for some reason it's not being addressed by Frsky. Perhaps we could try posting this problem on the RC groups TD receiver thread for more information?

**Comment by pld74** [comment]
Posted this long ago, still waiting for a resolution... https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/1892

**Comment by mawzthefinn** [comment]
Firmware 1.0.8 is out for the TD R10, is the issue still occurring? I tested on my TD R10 with 1.0.8 and it's working correctly.

**Comment by Mury123** [comment]
Hi, yes I flashed 1.0.8 and the voltage now reads correctly. Thanks for following this up.Regards, Alan

Sent from Sky Yahoo Mail on Android 
 
  On Wed, 26 Apr 2023 at 1:03 am, ***@***.***> wrote:   


Firmware 1.0.8 is out for the TD R10, is the issue still occurring? I tested on my TD R10 with 1.0.8 and it's working correctly.

**Comment by mawzthefinn** [comment]
Closing as it is confirmed fixed on TD R10 1.0.8

**Comment by xet303** [comment]
Closing as it is confirmed fixed on TD R10 1.0.8
