### ISSUE TITLE
Telemetry comparison

### ISSUE THREAD

**Issue by Target0815** [FrSkyRC/ETHOS-Feedback-Community#2163]
Hi,

I have started a comparison of the telemetry sensors between Ethos and OpenTX. Thereby I noticed some errors in Ethos. Source of the sensors is a Flight Control (Matek F405-Wing) with Arduplane 4.3.1.

Currently in comparison are Crossfire CRSF and ExpressLRS CRSF. Planned are FrSky's S.Port, F.Port and FBUS.

You can comment here or directly in the spreadsheet.

https://docs.google.com/spreadsheets/d/1nHlwnFdK_j8F-yItrQvbQgcP_zPOFuW6jiPu98MuaBI/edit?usp=sharing

**Comment by mawzthefinn** [comment]
Interestingly, according to the TBS Crossfire manual, Baro Alt is not supported as a valid CRSF sensor but Baro Vspd is

https://www.team-blacksheep.com/tbs-crossfire-manual.pdf page 56 has a list of all sensor types that are in the official CRSF spec.

**Comment by koakumaping** [comment]
> 

already supported by edgetx developer. tbs team agree added it.

**Comment by bsongis-frsky** [comment]
Alt and VSpd should work in Ethos in 1.4.4

**Comment by bsongis-frsky** [comment]
Please check and report here if anything is wrong in 1.4.4 (except RSSI and Attitude which have been fixed since)

**Comment by mawzthefinn** [comment]
VSpd works, but the vario function config is still missing in 1.4.4

I'm not seeing Baro Alt on ELRS

**Comment by Target0815** [comment]
> VSpd works,

According to my list not with Ethos 1.4.4 ... I need to have more information about your equipment, then I can check it.

**Comment by mawzthefinn** [comment]
HappyModel ES24TX and a Matek 6ch PWM/Vario receiver.

**Comment by bsongis-frsky** [comment]
Vario function added to CRSF Vario:

![image](https://user-images.githubusercontent.com/50834778/206707059-7bae7718-1b7b-44d1-a155-eda9c37aa891.png)

**Comment by Target0815** [comment]
The issue is not settled yet ...

ExpressLRS still has a telemetry problem with the RSSI values:

The value RxRSSI1 is not displayed at all, at RxRSSI there is a value, but it never changes when the distance transmitter to receiver increases or decreases.

Furthermore, no value is displayed for TxRSSI.

In comparison, all 3 values are present and plausible for Crossfire.
