### ISSUE TITLE
Twin X-Lite Emergency Mode 

### ISSUE THREAD

**Issue by j-watkiss** [FrSkyRC/ETHOS-Feedback-Community#2358]
Radio enters emergency mode when unplugged from USB in FrSky Suite mode.
Behaviour is the same regardless of whether drives are properly ejected or not.
FW 1.4.6

**Comment by yak-54** [comment]
I had this happen as well on an x12s with ethos 1.4.6 
others as well 
[https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2355](url)

**Comment by yak-54** [comment]
Had this issue as well on an X12S and it froze as well on ethos 1.4.6
there are others as well even X9 
ethos and windows its not happy

**Comment by MrD-RC** [comment]
Maybe I closed my issue too early 🤣 https://github.com/FrSkyRC/ETHOS-Feedback-Community/issues/2355

**Comment by j-watkiss** [comment]
> Maybe I closed my issue too early 🤣 #2355

maybe. my reason for plugging in USB was to put on the audio files, however. Had not noticed before this. Could it be related in some way?

**Comment by MrD-RC** [comment]
Honestly, I don't know. All I did was delete everything in the audio/en directory. Then copied all the files from the 1.4.5 audio_en.zip file to the audio/en folder. Then ran the update out if date components part again in ETHOS Suite. After that, disconnected the USB cable and no emergency mode. 

I only did it as I thought I had half the wrong voices. There were these ropey American voices and these lovely British voices. So I wanted to make sure all sounds were the same. Then realised the lovely British voice was actually from my sound pack 🤦🏼‍♂️ So now I'll need to recreate all the ETHOS system voices because it now annoys me lol

**Comment by j-watkiss** [comment]
@MrD-RC Let me know when you do that, the new voice hurts my soul :D

**Comment by arshish1612** [comment]
Same issue of Emergency Mode with the X20S also after updating to 1.4.6

https://photos.app.goo.gl/Nc6gNSSrAHt2Gj149

**Comment by arshish1612** [comment]
> Honestly, I don't know. All I did was delete everything in the audio/en directory. Then copied all the files from the 1.4.5 audio_en.zip file to the audio/en folder. Then ran the update out if date components part again in ETHOS Suite. After that, disconnected the USB cable and no emergency mode.
> 
> I only did it as I thought I had half the wrong voices. There were these ropey American voices and these lovely British voices. So I wanted to make sure all sounds were the same. Then realised the lovely British voice was actually from my sound pack 🤦🏼‍♂️ So now I'll need to recreate all the ETHOS system voices because it now annoys me lol

This Fix works only for the first disconnect. If you restart the TX connect it to EthosSuite it again - The issue will reoccur

**Comment by Target0815** [comment]
Most likely some script is causing the problem. To test, simply remove all scripts and then add them back one by one.

**Comment by j-watkiss** [comment]
The only script on the radio for me is the ELRS LUA. But I will try later

**Comment by strgaltdel** [comment]
scripts could be one root cause,
but on rcg there is a discussion that EM may be caused by connecting the tx in "Ethos mode".
enter bootloader mode and connect tx to your pc would be fine.

**Comment by arshish1612** [comment]
> scripts could be one root cause, but on rcg there is a discussion that EM may be caused by connecting the tx in "Ethos mode". enter bootloader mode and connect tx to your pc would be fine.

It's me on RCG that faced and posted the issue. And I can confirm that I do not have any scripts.

**Comment by Target0815** [comment]
I have seen your video. I can't reproduce the problem on an X18S. But I noticed that on your PC the Explorer windows do not open when you connect via USB. Is this always the case?

**Comment by arshish1612** [comment]
> I have seen your video. I can't reproduce the problem on an X18S. But I noticed that on your PC the Explorer windows do not open when you connect via USB. Is this always the case?

Its a Mac, not a PC. Thats probably why. Not sure

**Comment by MrD-RC** [comment]
I'm using Windows.

The Explorer apps opening or not is a choice you can make in Windows. You can have it do nothing when a new drive is connected, or open it in Explorer. This is not related.

But, the connection via bootloader or via ETHOS could be on to something. I did switch in to bootloader on the time it didn't enter emergency mode.

**Comment by j-watkiss** [comment]
The fault does not occur if you select serial or joystick connection, either. Only if you select ethos suite when connected

**Comment by arshish1612** [comment]
Hope this one is fixed with the next release.

**Comment by bsongis-frsky** [comment]
Fixed in next 1.4.7

**Comment by drummaker** [comment]
Well sort of fixed... Ethos Suite 1.4.7 updates to 1.4.6 so problem still exists.... I reinstalled 1.4.7 suite and same results... I manually updated firmware and now 1.4.7   NOW it works when unplugged...Come on guys... Ethos Suite is and should remain a great tool... People should use it BECAIUSE it keeps them from having issues,  not cause them... this is the third time this kind of stuff has happened
