### ISSUE TITLE
new x20 pro sound and volume bad.

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#2972]
Just got a x20 pro volume is much lower than my x20s and sound is very tinny compared to my x20s.  very dissapointing as i thought the sound would be much better than the x20s as it is supposed to have an amplifier.

**Comment by mawzthefinn** [comment]
I just compared my X20 and X20 PRO directly.

Volume is identical, with both set to max. 

The X20 PRO is very slightly tinnier, as I'd expect since the case doesn't provide any damping unlike the plastic case. It actually sounds to me like teh X20 is being slightly muffled, sounds are clearer on the X20 PRO.

**Comment by williajgr** [comment]
Maybe there is something wrong with mine. At half volume the pro is very noticeably quieter than my S I have to set the pro to 3/4 volume to equal my S at 1/2 volume.  Doesn’t make sense as there I suppose to be an amplifier in the pro. The sound quality is very disappointing, no low tones.  My tiny metal iPhone has infinitely better sound.  Should I take it apart and replace the speaker?Sent from my iPhoneOn Oct 16, 2023, at 3:14 PM, mawzthefinn ***@***.***> wrote:﻿
I just compared my X20 and X20 PRO directly.
Volume is identical, with both set to max.
The X20 PRO is very slightly tinnier, as I'd expect since the case doesn't provide any damping unlike the plastic case. It actually sounds to me like teh X20 is being slightly muffled, sounds are clearer on the X20 PRO.

**Comment by Nicholas-Luoyi** [comment]
What is the firmware version of your X20 Pro?

**Comment by williajgr** [comment]
1.4.12 firmwareSent from my iPhoneOn Oct 16, 2023, at 10:20 PM, FrSky-Luo ***@***.***> wrote:﻿
What is the firmware version of your X20 Pro?

**Comment by enzo-molinari** [comment]
The X20S is also louder for me. In order to understand the announcements, I have to turn the volume on the X20Pro higher than on the X20S on the airfield.
The announcements are in German. Maybe it's because of the original German male voice that I have to turn up the volume on the Pro? The women's voices could perhaps also be heard in a quieter tone?
The firmware version of Ethos is 1.4.12.

**Comment by mawzthefinn** [comment]
I do think the PRO has a different gain curve applied, so it may have different mid-position volumes from other radios.

When I compare at full volume, overall volume is the same.

**Comment by aeroplanebelg** [comment]
hello mr Songis, I also received my x20pro and I cannot hide my disappointment from you. The sound is really bad compared to my x20s, it is certainly more (pure?) but distorts very quickly. Come and tell us that it's due to the aluminum casing hum... my eye!!!! just place the bluethooth system on a well-known external hp and there is no photo!! the x20s wins hands down! Now if we talk about the TTS sound....it's even worse!!! only available in English for the moment, it's almost incomprehensible...There's one more thing that's wrong, it's the loading of the models. Still compared to my x20s the loading of models is very very slow. (everything is on the radio memory, nothing on the SD) There you go, I'm not used to filling myself up but at the asking price, it's not acceptable. As a reminder, these radios are numbered and supposed to have been checked by an engineer!!! Which suggests that these faults are known by frsky.
I end as always by thanking Mr Songis and his team for their work.
ROBERT.R
ps. Overall, it's a very nice, well-thought-out radio but.....
there are these problems that spoil the party.
I hope you can improve things.

**Comment by bsongis-frsky** [comment]
- audio sound: I will forward your comment to the hardware team
- TTS: it's an external chip which speaks only English and Chinese, we cannot improve it
**- slow loading speed: I will check on Monday, the speed should be comparable to the SD speed**

**Comment by aeroplanebelg** [comment]
Mr Songis, thank you for your quick response.
Remove a doubt from me, the TTs chip will only speak these two languages?
Thank you. Robert.R
(French language and always the latest firmware.)

**Comment by andika207** [comment]
> I just compared my X20 and X20 PRO directly.
> Volume is identical, with both set to max.

mmmm.... so the digital audio power amplifier was pure marketing crap as usual and the devs are expecting to fix this with a firmware update ?

**Comment by yogikat** [comment]
I have some noise from the speaker when turning my radio on , it's happened for 1 sec . 
Did not happend in my x20s .

**Comment by woltervdberg** [comment]
I have the same experience. Both my X18S and X20S are significantly louder and sound a lot better. My X20 pro sounds very tinny and distorted especially at high volume. I am using the same language pack on all my radios so that can’t be it. As someone else mentioned I also hear the welcome message on my X20 pro even with the sound turned off. 

Although I can easily live with these issues, it annoys the crap out of me that some Frsky reps are claiming this problem doesn’t exist or is barely noticeable. This is a problem especially because better audio quality was one of the selling points of this radio.

**Comment by mawzthefinn** [comment]
Ok, first some facts, then some opinion.

1. If you are testing volume at any setting other than max, you are testing gain curve, not volume. 

I tested my X20 Pro vs my X20 at max, volume level was indistinguishable. At lower levers it differs. That’s gain curve differences, not volume


Now opinion. 

The stock ETHOS sound files optimized for the X20 are badly optimized for the Pro. Yes, they sound tinny. IMHO you need different compression and a lot more in the lower bands to make files that sound right on the X20 Pro. Those same files will likely sound muddy on the X20. It’s not a hardware issue, it’s mixing when the files are generated. The fundamental difference here is the case, the plastic cases muddy the speaker output.


There are real issues in the audio system, the click at boot and mute timing on startup are real (if minor) issues and the TTS quality in English is poor.

**Comment by andika207** [comment]
> the TTS quality in English is poor.

I knew ahead of time this was gonna be useless :no_entry:
I have just checked out the price on HorusRC and it now retails for 859 U$ and this is not a chinese new year holiday sale. 
This makes me think they are not selling that well and they expect to raise some sales with the color case editions.

**Comment by mawzthefinn** [comment]
The C20 Pro is now available outside the special package for the first 1000 units. The $859 price becomes $955 when you add the TD R18+audio jack switch that was in the launch package

**Comment by williajgr** [comment]
The issue is stale because nobody has fixed it.  Lots of people commented on it and agreed it was bad.Sent from my iPhoneOn May 3, 2024, at 10:03 PM, github-actions[bot] ***@***.***> wrote:﻿
This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.

**Comment by andika207** [comment]
> The issue is stale because nobody has fixed it.

they can't fix hardware weaknesses with a simple firmware code and I feel the X20 PRO **R** is the same crap with another dress

**Comment by KevinFairgrieve** [comment]
The startup "click" is fixed in 1.5.7

Sound is still a little on the low side though.

![X20](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/20424058/cbaa4d04-a90f-4ebd-8a53-76162c427130)

**Comment by it-walter** [comment]
Improved, but not completely fixed 1.5.7! But now it's already much better.Am 04.05.2024 um 18:16 schrieb Kevin Fairgrieve ***@***.***>:﻿
Fixed in 1.5.7
X20.jpg (view on web)
