### ISSUE TITLE
1.5 RC1 Sticky Logic Problem 

### ISSUE THREAD

**Issue by spoke2570** [FrSkyRC/ETHOS-Feedback-Community#3336]
In the pictured logic switch the trigger on condition has no effect on the switch. SE middle and SE NOT middle are the only drivers. SJ has no effect. 

Expected SE middle AND SJ down to start. Expected SE NOT middle to stop. 

![IMG_0507](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/9330938/89e49ad6-58c2-4408-afc4-a35301ece79d)

**Comment by Wolepo** [comment]
LS31 is only active if SE is in the centre. Therefore, a reset cannot work if SE is not equal to SE-.

**Comment by bsongis-frsky** [comment]
Exact, I wonder why you setup an Active condition

**Comment by spoke2570** [comment]
Sorry was typing with my thumbs last posts. 
The SJ is replacing another binary logic that goes true when the throttle stick is low. The idea being that the SE- and throttle low activate the throttle stick so it won't start inadvertently by just going to SE-. To not test that low throttle stick logic I replaced it with the momentary SJ.

I expect (and have been using until the 1.5 RCx) that once !SE- has been met the LS31 goes false until SE- and SJdown happen at the same time again. This is not the case. Note SJ is a momentary with up as default.
What happens stepwise:
Load model ->LS31 false
SA-               ->no change
SJdown        ->LS31 true
SJup             ->no change  
SJdown        ->no change  
SJup             ->no change  
!SA-              ->LS31 false
SW-              ->LS31 true 
!SA-              ->LS31 false
SW-              ->LS31 true 
At this point the model needs to be reloaded to clear the "Trigger ON Condition." SJ is no longer part of the deal.

**Comment by spoke2570** [comment]
@Wolepo This has been working with every ETHOS until the 1.5 RCO release. Once the LS goes false both the active condition and the trigger on condition should need to be simultaneously true to trigger the true LS. That is not the case, here.

**Comment by Wolepo** [comment]
Only Bertrand can answer whether this is different now.

**Comment by spoke2570** [comment]
It works in 1.4.7, so something changed.

**Comment by spoke2570** [comment]
Works in 1.5 RC0 but can be fooled with rapid switch flipping.

**Comment by Wolepo** [comment]
An undefined period of time occurs during the switching of SD. It is therefore left to chance which of the two positions is active first. I would therefore delay the trigger positions slightly to ensure that SE- is valid first and then SJ or !SE-.

**Comment by spoke2570** [comment]
..and I have already implemented that. My consideration is that a logic switch should fully reset when it goes false.

**Comment by bsongis-frsky** [comment]
Is this issue fixed in 1.5.7?

**Comment by spoke2570** [comment]
I will check in about 2 hours.

**Comment by spoke2570** [comment]
This is not fixed, as of 1.5.7 on my X20S
SHdown (on trigger) and SEmiddle (active condition) are not required to be simultaneously true for the LS to become true in many cases.

**Comment by spoke2570** [comment]
Still problematic in 1.5.8 
I modified my test to use 3 separate switches to remove any possible recursive logic. Active Condition (AC) is on a 3 position switch(SE-). Trigger Off (TOFF) is on a 3 position switch (SA-). Trigger On (TON) is a momentary switch (SJdown) and used as a momentary pulse.

1) The mix should default to false. Currently if AC, and TOFF are both true when the TON becomes true the LS becomes true. This mix should be false if any part of the  constants a false. In this case the LS should be never become true because TOFF is already true. 

2) When the mix becomes false all parts of the switch should be reset. Currently the active condition can be used to toggle the LS between true and false repeatedly until the TOFF is met (The TON remains false, here.). It should be that once the LS goes false (for any reason TOFF met or AC unmet) the AC and TON should need to be simultaneously true (and the TOFF false) to trigger the LS true state again.

**Comment by spoke2570** [comment]
still a problem 1n 15.10. 
When TOFF is true before TON  is pulsed the switch goes true until TOFF is cycled false and back to true. In this case the LS should never go true. 
TON is not reset when the LS goes false. This allows the AC to toggle the LS making it behave not like a sticky at all.
