### ISSUE TITLE
throttle cut did not get off when throttle is 100%

### ISSUE THREAD

**Issue by LuHaGH** [FrSkyRC/ETHOS-Feedback-Community#3889]
For Helis or Gliders I put Thr. on a Switsch (SA) and set up a three steps throttle curve.
![screenshot-2024-04-22-47778](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/93262335/c141b042-5399-4950-9560-7cf3c62781ee)
 I put throttle cut to (SE) and set the trigger value to 100%
In the low and middle position of SA everything works fine, I'm able to switch Thr. Cut with (SE) on and off.
But I'm not able to do this in the high position of SA
![screenshot-2024-04-22-47785](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/93262335/e4eebafd-4188-482c-b468-14140bd02443)
![screenshot-2024-04-22-47788](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/93262335/3ecb63e4-33dc-40c9-90c6-4008eabe37da)

It is the same when you use the Thr. stick, When it is calibrated well at 100% you need a little jitter below 100% to get throttle cut deactivated. You should test on "<=" not only on "<" I think.

**Comment by mawzthefinn** [comment]
Just tested this on my radio (1.5.6 FCC) and it's working correctly with Trigger value at 100%.

**Comment by LuHaGH** [comment]
I have here three 1.5.6 LBT Radios X14S, X18S and X18SE all with the same behaviour. Did you tested with switch or just the throttle stick? The jitter of the throttle stick often did not show the issue.

**Comment by mawzthefinn** [comment]
Switch on SA, duplicating the screen shots provided.

**Comment by LuHaGH** [comment]
[throterr.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15067768/throterr.bin.zip)
I create a new model in the X18S 1.5.6 Simulator only with throttle. Press SA until Thr is 100% than press SF for throttle cut. You can't switch throttle on again by pressing SF until reducing SA to 0% or -100%.

**Comment by joy2417** [comment]
Yes, same problem here. I can reproduce the bug even with ETHOS 1.4.17 and it is still present in 1.5.6.

**Comment by bsongis-frsky** [comment]
Is it fixed in 1.5.7? We have worked on Throttle events in this version ...

**Comment by LuHaGH** [comment]
No, it is not fixed in 1.5.7. I just tested it in 1.5.7 with the X18S Sim and my X14S student transmitter.

**Comment by joy2417** [comment]
The error is still present in 1.5.7.
With the [throterr.bin.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15067768/throterr.bin.zip) from LuhaGH it is easy to reproduce it.

**Comment by bsongis-frsky** [comment]
Thanks @joy2417 I will work on in when I find time, so that it is fixed in 1.5.8

**Comment by joy2417** [comment]
In the Nightly 1.5.8 the bug is still present.

**Comment by joy2417** [comment]
NO!
OK, the described problem is gone, but now you are not able to cut throttle if throttle is at 100%.
This is extremely dangerous.

**Comment by bsongis-frsky** [comment]
What???

**Comment by bsongis-frsky** [comment]
![image](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/50834778/88dc9035-2fa7-4703-b8b3-79099a801875)

**Comment by bsongis-frsky** [comment]
Would you please explain the scenario where it is dangerous?

**Comment by joy2417** [comment]
When you are at 100% throttle the "throttle cut" will not cut the throttle any more. This is dangerous in an emergency if you have to stop the engine.

Set throttle input to SE and "throttle cut"to SF with trigger value 100%. 
https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15067768/throterr.bin.zip is a good example.

**Comment by bsongis** [comment]
@joy2417 you are right, thanks a lot!

**Comment by bsongis** [comment]
@joy2417 what is your board? I will launch a quick compilation of a binary for you

**Comment by joy2417** [comment]
I use the X14S for testing

**Comment by joy2417** [comment]
Perfect. Now it works fine, thank you.

**Comment by mszulen** [comment]
> When you are at 100% throttle the "throttle cut" will not cut the throttle any more. This is dangerous in an emergency if you have to stop the engine.
> 
> Set throttle input to SE and "throttle cut"to SF with trigger value 100%. https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/15067768/throterr.bin.zip is a good example.

The "Trigger value" sets the point where throttle cut can activate. Set it to +100% and it will cut at any throttle position.
Value lower than 100% might be useful to prevent accidental throttle cut during flight, but as said - set it to +100% and it will work like you want.

**Comment by mszulen** [comment]
The "Trigger value" seem to let me cut the throttle value to -100 even if the throttle stick is up. That is good.
What is not good (or I haven't found a way to do it) is that when the throttle cut is active and I move the throttle up then deactivate the throttle cut - the throttle value immediatelly jumps to max value starting the motors.

What I'd like to do is:
1. Throttle is down and throttle cut is down.
2. Move throttle up - throttle cut is active
3. Deactivate throttle cut and still have -100% on throttle channel until I move the throttle back down. After that throttle works normal.
