### ISSUE TITLE
Critical throttle cut and throttle hold issue

### ISSUE THREAD

**Issue by azaz44** [FrSkyRC/ETHOS-Feedback-Community#4016]
Ethos 1.5.7

I don't know if this problem existed before (in 1.4.x) because I didn't use built-in throttle mix up to now. Now in 1.5 throttle mix was improved and looks great so I use it. 

Problem is:
- releasing throttle-cut outputs normal throttle value for a short time even when throttle-hold is engaded. Then after a short time it comes to a proper value which is set for throttle-hold

To reproduce I made a clean model ('other' type) and just added one throttle mix. Setup like this:

![20240511_184112](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/8083d93e-905e-42b0-aa29-0c4908811b07)

![20240511_184118](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/7f75360d-0f5b-49f6-ba40-f413ddb11004)

![20240511_184125](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/b1ebe501-d8c9-4641-8ce6-2e3dba785a67)

![20240511_184128](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/42830563/4aedb13d-6a41-4768-9d83-fa565abe53b9)

(sorry for photos quality, I make tthis report while at the field)

And this is what happens when I flip throttle cut, while throttle hold is enabled all the time

https://youtu.be/Egdh166_Up0?si=NxE51a4uMInujmQH

I marked it as critical, because it caused an unwanted spoolup in one of my helicopters.

**Comment by bsongis-frsky** [comment]
I think it is already fixed in 1.5.8 nightlies, would you please confirm?

**Comment by azaz44** [comment]
> I think it is already fixed in 1.5.8 nightlies, would you please confirm?

I tested and problem still exists in todays (2024.05.13) 1.5.8 nightly.

**Comment by spoke2570** [comment]
It is somewhat intermittent on my X20S in todays (2024.05.13) 1.5.8 nightly. Takes many flips to make the error happen, then happens for several flips, takes several flips to make it happen, etc.

**Comment by azaz44** [comment]
Issue is still there in 1.5.12.

**Comment by azaz44** [comment]
Issues still there in 1.5.18, this is really an issue for helicopters with governors, as throttle not low for even this flash of a seconds starts spoolup procedure for a short time and will spil blades.

**Comment by azaz44** [comment]
Still valid. This issue is actually critical, I think it should get a bit higher priority.

**Comment by Hartinger** [comment]
I have observed a problem that may be related to the one described by the author of this issue (tested with ETHOS 1.6.1 on Tandem X20S and Twin X14S).

On power-on or selection of a model, with throttle not idle and throttle-cut not engaged, the corresponding warnings are displayed (throttle not idle, switch warning). If the warnings are then accepted (without changing any controls) the throttle channel is not at -100% but reflects the position of the throttle control, although Sticky in the throttle mixer is selected. Throttle-cut should only ever be removed if the throttle control element is moved to the idle position.

The problem described here was not present in ETHOS 1.5.19.

**Comment by hrenz** [comment]
Test with ETHOS V1.6.2

Motor safety switch (lock) with SA^
SRFF ON
Trigger -90%
Test with throttle stick at +50%

Switch off transmitter
Throttle stick is at +50%
Motor lock “accidentally” set to SAv (i.e. motor is already enabled)

Switch on transmitter, warning appears, press away,
Engine starts immediately!
This should not happen!

----
But if the switch is still set to engine disabled, nothing happens,
Throttle channel remains locked, nothing happens, 
The throttle stick can be moved,
If the throttle stick is then somewhere and the engine lock is only now released, nothing happens either
The throttle stick must first go to -100%
before the channel follows, that's ok.

-----
Either the SRFF is not set at all when the transmitter is booted, or it is reset immediately.
or the position of the motor safety switch is not queried or queried too late.

----
or a “side effect” of the changed SRFF?
or program sequence or program sequence during booting ??

-----
I don't think it's due to the SRFF changes
because they were only made from V1.6.1 and optimized from V1.6.2.

The error has been occurring since V1.6.0, 
up to V1.5.19 it was still ok?

I think this is due to the improved compiler settings from V1.6.0 
and that there is now a timeout during booting before the switches and SRF are set/locked.

I think this is the only way it can be!

**Comment by azaz44** [comment]
I think guys you need to raise a new issue, because it looks like entirely different issue than the original. Maybe just link this one in the new one. This should bring attention to it. I think closed issues might be checked less frequently especially if you don't mention Bertrand directly.

**Comment by Hartinger** [comment]
I have raised #5162 to cover the new problem.
