### ISSUE TITLE
Now 1.5.9 with the update of the curves screen, in Spanish,The names and type overlap.

### ISSUE THREAD

**Issue by jasalca** [FrSkyRC/ETHOS-Feedback-Community#4086]
![IMG_4424](https://github.com/FrSkyRC/ETHOS-Feedback-Community/assets/87758703/7e468432-c263-4329-a3a4-304ed1ebef96)
 My radio is X20 Pro AW. 1.5.9 FLEX

**Comment by jasalca** [comment]
In english ,Custom= 6 letters
In spanish, Personalizado= 13 letters

**Comment by bsongis-frsky** [comment]
This one should be fixed in latest 1.5.10 nightlies!

**Comment by jasalca** [comment]
Hello Bertrand, sorry I know you have a lot of of work, I wanted to tell you that this bug is still the same.

**Comment by bsongis-frsky** [comment]
![image](https://github.com/user-attachments/assets/bf146845-66c9-433e-84cb-8d080ca784f1)

Perhaps it's possible to reduce the word "Personalizado"? It is very long and doesn't bring so much information ...

**Comment by bsongis-frsky** [comment]
Like this?

![image](https://github.com/user-attachments/assets/72fc9f57-bdc8-4550-a551-fae0b931b8c3)

**Comment by jasalca** [comment]
Yes of course!!
