### ISSUE TITLE
Transmitter doesn't recognize that receiver is shut off 

### ISSUE THREAD

**Issue by williajgr** [FrSkyRC/ETHOS-Feedback-Community#4621]
Transmitter doesn't recognize that receiver is shut off .    When i turn the transmitter off first and then turn the receiver off the transmitter doesn't recognize that it is turned off.

**Comment by Dsrenger** [comment]
How should the transmitter recognize that the receiver is off if you switch the transmitter off first? What you never should do. 

Or is it a typo?

**Comment by williajgr** [comment]
the transmitter doesn't actually go off just gives you the warning that the receiver is still on.  then when you turn the receiver off the transmitter then turns off.  Frysky has worked like that always.

**Comment by jasalca** [comment]
It works perfectly for me. If I try to turn off the transmitter with the receiver on, it warns me that it is on.Anything else doesn't make sense.

**Comment by williajgr** [comment]
It is supposed to shut the transmitter off when one turns the receiver off.  Tandem x20RSSent from my iPhoneOn Oct 11, 2024, at 9:49 AM, jasalca ***@***.***> wrote:﻿
It works perfectly for me. If I try to turn off the transmitter with the receiver on, it warns me that it is on.Anything else doesn't make sense.

**Comment by itizmeunderscoreca** [comment]
Happens to me also
turn of the rx and the tx doesn't see it shut down, still shows signal strength as well. when turning off the tx you get a warning the rx is still on. need to see if this is a resolved issue that an update will cover.

**Comment by pmullen503** [comment]
> It is supposed to shut the transmitter off when one turns the receiver off.

It's never worked that way. If you lost telemetry from your receiver it would shut down your TX!

Under certain circumstances it does take a longish time after the receiver is off before you get a "telemetry lost" warning. But that's a minor annoyance.

**Comment by williajgr** [comment]
No you don’t get it.  When you turn the transmitter off first, then you get a warning that that the receiver is still on, then you turn off the receiver off and the transmitter doesn’t see that you turned the receiver off.  Does work correctly on some of my transmitters.  I have been a FrSky user for over 10 years so I know what I am talking about. You don’t.Sent from my iPhoneOn Oct 11, 2024, at 4:59 PM, pmullen503 ***@***.***> wrote:﻿

It is supposed to shut the transmitter off when one turns the receiver off.

It's never worked that way. If you lost telemetry from your receiver it would shut down your TX!
Under certain circumstances it does take a longish time after the receiver is off before you get a "telemetry lost" warning. But that's a minor annoyance.

**Comment by mawzthefinn** [comment]
What RF Module firmware? There's a bug in TD ISRM Pro 1.1.13 that would cause this as it doesn't properly register 2.4G telemetry stopping on TD receivers. It's fixed in 1.1.14

**Comment by itizmeunderscoreca** [comment]
Hi Adam
I am running as enclosed and I assure you this happened last weekend running exactly this. Turn off rx, still see the 2.4 signal on tx, and the tx says rx is still on.
![x20](https://github.com/user-attachments/assets/196fc141-10a3-4471-88cf-ab775791d783)

**Comment by itizmeunderscoreca** [comment]
I actually found a log file for my 330LT setup with a TDR18 and TDMX. I can see there is an issue perhaps with the R9M Power. Sorry it is the only log file I have like this but it is from last weekend.
![r9m](https://github.com/user-attachments/assets/8052d2e2-5dc3-40b1-a0c1-f4c196d13939)

**Comment by williajgr** [comment]
i have the updated firmware hw 1.0.4 fw 1.1.14

**Comment by mawzthefinn** [comment]
This is working correctly for me on FW 3.0.0 Beta. Should be resolved once that is officially released

**Comment by williajgr** [comment]
Thanks.  I have a new problem with a td sr18 receiver but don't want to create an issue as it is probably something i have done.  set it all up and it worked as it was supposed to (delta wing). Then i started playing with things.  changed the 2nd elevator output 2 (channel 6) to channel 2. At that point channel 5 and 6 stopped working as a delta wing and no stabilization on either channel.   I rebuilt the model ,put old firmware on the receiver then the new firmware back again, reset the stab stuff recalibrated it several times, and nothing would make it work again. You are the only one that might figure out what is wrong.
    Thanks for any help.
       Joe

________________________________

**Comment by itizmeunderscoreca** [comment]
I still have issues but it is winter so it is not like I turn the rc and a tx on often at all. The last issue I had was 2 weeks ago using a fully updated new TDSR6. I posted a question about this over on RCG to see if I am alone in this, apparently so.

https://www.rcgroups.com/forums/showpost.php?p=53553751&postcount=242

**Comment by mawzthefinn** [comment]
Closing old resolved issue
