### ISSUE TITLE
Ethos on MAC does not recognise drives

### ISSUE THREAD

**Issue by pandjarov** [FrSkyRC/ETHOS-Feedback-Community#4847]
I switched to an M3 MBP and now it fails to recognize the drives when my X20Pro is linked via USB to the EThos app. This results in failure to update the outdated components. I am using the latest Ethos app Version 1.5.12 (1.5.12)

![Screenshot 2024-12-06 at 11 45 45](https://github.com/user-attachments/assets/202bcd12-74f6-4067-9e9d-199a827a9bcb)

**Comment by mawzthefinn** [comment]
It's fundamentally a MacOS 15 issue. MacOS 15 has some enduring issues with FAT32 external storage right now (I'm seeing it with multiple devices, not just my radios). 

Plugging the Radio in after ETHOS Suite is open usually solves it.

**Comment by mtschaff** [comment]
I see it frequently on my M1 Mini.  I click Ignore on both, then switch to Bootloader mode, click Ignore on both again, and switch back to Ethos mode.  Some times it takes repeating this sequence, but then those warning dialogs go away, and the Flash and Radio drives mount normally.

**Comment by kramgrand** [comment]
On my M2 I plug in a mini USB hub that takes an SD card.  If I plug any SD card in first and then plug the radio into a USB port it loads the Flash and Radio drives without error.

**Comment by sjorger** [comment]
Hello,
I have the same problem with my MacOs 15.1.1.
I contacted Apple support but they do not offer any solution for now.

**Comment by mszulen** [comment]
Yeah, it's on the Apple's side.
Run the disk manager and mount the drive manually. It works then.
I know, it's pain in the ass but doesn't look like there's a better workaround

**Comment by FriedelXT** [comment]
Problem is fixed after update to 15.2

**Comment by sjorger** [comment]
I confirm, MacOS Sequoia update 15.2 fixes the problem.

**Comment by kramgrand** [comment]
I can confirm it is   Not fixed   on MacBook Air M2.   (MacOS Sequoia update 15.2).   It Occasionally works as it should
Radio at 1.5.19  Flex

**Comment by FriedelXT** [comment]
I can comfirm on MacBook Air M3 it works too

**Comment by mszulen** [comment]
15.2 on M1 and it does NOT work (unless manually mounted) - the drive is visible under disk manager but NOT automatically mounted.

**Comment by mszulen** [comment]
I guess this issue can be safely closed as it's completely NOT related to Frsky. It's a Mac OS system issue.
