### ISSUE TITLE
IT Audio pack missing files

### ISSUE THREAD

**Issue by mgsanna** [FrSkyRC/ETHOS-Feedback-Community#5060]
Hi @bsongis-frsky , even I've already updated the it.csv audio file with translation of new lora and telemetry alerts, the audio files are missing....
Is it normal? can we provide ITA audio updated pack for RC3 of 1.6.1 ?

Thanks in advance
Marco

**Comment by bsongis-frsky** [comment]
Done, please download again the audio pack from 1.6.1 RC3!

**Comment by mgsanna** [comment]
> Done, please download again the audio pack from 1.6.1 RC3!

As usual Thanks ! 
have a nice day Bertrand!!

**Comment by mgsanna** [comment]
Hi @bsongis-frsky Bertrand these files are still missing on 1.6.1. rc3 audio pack

system/rssi-2g4-lost.wav,2 giga 4 telemetria persa,,
system/rssi-2g4-recovered.wav,2 giga 4 telemetria recuperata,,
system/rssi-2g4-critical-warning.wav,attenzione 2 giga 4 RSSI critico,,
system/rssi-2g4-low-warning.wav,attenzione 2 giga 4 RSSI basso,,
system/rssi-lora-lost.wav,lora telemetria persa,,
system/rssi-lora-recovered.wav,lora telemetria recuperata,,
system/rssi-lora-critical-warning.wav,Attenzione RSSI lora critico,,
system/rssi-lora-low-warning.wav,Attenzione RSSI lora basso,,
system/rssi-900m-lost.wav,900 mega telemetria persa,,
system/rssi-900m-recovered.wav,900 mega telemetria recuperata,,
system/rssi-900m-critical-warning.wav,Attenzione RSSI 900 mega critico,,
system/rssi-900m-low-warning.wav,attenzione RSSI 900 mega basso,,

**Comment by mgsanna** [comment]
@bsongis-frsky 
I've noticed they are missing only in the milestone rc3 audio.zip release and they are present on audio directory of 1.6 repository

If you Like I can Upload in RC3 release the audio-it.zip corrected...
EDIT 
I have uploaded to the RC3 Release the correct audio-it.zip (taken from audio folder of ETHOS-Feedback-Community
