### ISSUE TITLE
irx4 lite module telemetry

### ISSUE THREAD

**Issue by Danmcmahon1** [FrSkyRC/ETHOS-Feedback-Community#5104]
Not sure if this belongs here but multi module git hub said it was not their issue
I have an x20s bound to an e-flite Draco
The plane fly's fine and I have flown it several times, but I have 2 issues with telemetry

First the temp is reading about 40 degrees when it is 70 degrees Fahrenheit
on the widget screen I have the units set to Fahrenheit - do I need to change something else?

2nd the rpms are reading about 6-10 times faster than what it appears to be
on the widget screen for the ESC RPM I have the following settings which were factory default
range 0r/m to 250000r/m
Mode is set to prop
average is set to 1 sample
blades is set to 1 - should it be 4?

I also have the settings

under the info tab in my radio - the external module is called multimodule 1.3.4.0
under the RF system tab the protocol is set to spectrum DSMX-2F

Thanks

https://github.com/user-attachments/assets/82509167-9b0d-4054-9e2a-65a4a699b02a

**Comment by frankiearzu** [comment]
The module just passes the raw telemetry data to the TX, where some math is done to be properly displayed.  The Multi-Module don't do anything besides just pass blindly the telemetry data.


I am assuming that you have an Avian ESC.

Do you have the DSMTools installed? You can go to Telemetry and ESC Status. It will show the raw values from the Avian ESC on the reporting unit (Celsius) and the RAW RPM.    With this, we can compare with the Widget.

The # of blades will divide the RPM by that number.  Don't know what is the formula in Ethos. but in EdgeTX was another multiplier. So the RPM was (RawRPm * multiplier) / blades

DsmTools download:
https://github.com/frankiearzu/DSMTools

For Ethos, download the DSMTools Suite.

**Comment by Danmcmahon1** [comment]
So I was able to correct the RPM by adjusting the value of the Props
The temp when I select Celsius is correct
however, when I change the widget to Fahrenheit it is not correct
is there somewhere I can change the formula?

**Comment by bsongis** [comment]
If I am not mistaken the DSM2 sensor returns a temperature in Fahrenheit. If you want to display Celsius you just have to select Celsius, the conversion is automatically done by Ethos and it seems you are saying it is correct!

**Comment by Danmcmahon1** [comment]
The temp in Celsius is correct. It reads 20 degrees
but when I change to Fahrenheit it reads 39 degrees
It should read 68 degrees

https://github.com/user-attachments/assets/3a3abb43-a96d-4d2c-b647-398afcd65bd6

**Comment by bsongis** [comment]
Which is your Ethos version?

**Comment by bsongis** [comment]
This bug has been fixed in 2023, July!

**Comment by Danmcmahon1** [comment]
where was the bug fixed
I have Ethos version 1.6.1
multimodule 1.3.4.0

**Comment by bsongis-frsky** [comment]
The conversion is wrong. It is executed without taking account of the decimals.
Here "200" is received, which is converted to "392". Then with one decimal removed, it's displayed "39°F", which is wrong!

**Comment by bsongis-frsky** [comment]
Would you please check that the bug is fixed in the next Ethos 1.6.2 nightlies? I don't have this sensor at hand!

**Comment by frankiearzu** [comment]
I started suspecting a conversion problem when Dan said that Celsius was fine (i think the source is C for this sensor.)
I fixed a similar conversion problem in EdgeTX.. the formula assumes no decimal places.
The same conversion problem happened with FrSky sensor temps when you changed the GUI to more decimals.

Formula:
F= (C × 9/5) + 32
The "32" constant needs to be adjusted depending on the number of decimals, to 32, 320, 3200, etc.

Using raw  C=200  (20C with 1 decimal)
F = (200 x 9/5) + 32
F = 360 + 32
F = 392 = 39.2 F (wrong)

The general formula:
F= (C × 9/5) + 32*(10^decimals),

where decimals =  max(sourcePrec,destPrec).      (this accounts for when later GUI changes display precision to more decimals)

Using raw C=200  (20C, 1 dec)
F = (200 x 9/5) + 32*(10^1)
F = 360 + 320
F = 680 = 68.0 F (correct)

Using raw C=2000  (20C, 2 dec)
F = (2000 x 9/5) + 32*(10^2)
F = 3600 + 3200
F = 6800 = 68.00 F (correct)

https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/telemetry_sensors.cpp#L694

When converting from a source with 1 decimal to a GUI setting of 2 decimals, also needs some adjustments:
The original value needs to be adjusted   (newValue = originalValue * 10 ^ (destPrec - sourcePrec) when  destPrec > sourcePrec before the conversion, and the opposite after the conversion  when   sourcePrec > destPrec 
On OpenTX was done with loops, but changed it to use a small "power10" table.

https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/telemetry_sensors.cpp#L684

**Comment by frankiearzu** [comment]
Not a home for a real radio, but tested with the X14S/X20 sim of 1.6.2.
Seems that the conversion when decimal places are > 0 is still not correct.

This "Tools" LUA script creates a few "my Temp" sensors where the protocol unit is C, and the display is F.
On a simulator, start by deleting the current sensors, then in sys->tools, run the "Temp Conversion" tool to create the sensors.
It will create 3 sensors, all representing 20C.   one with 0 decimals, 1 decimal, and 2 decimals, but display in F.

Another part that was an exception when i was doing the fix for EdgeTX was when the protocol was 1 decimal. and the display was 2  (displayPrec > protocolPrec in Ethos), i needed to adjust the power10 to use to convert the constant "32" in the formula:

https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/telemetry_sensors.cpp#L694

if the source was 1 decimal, and the display is 2 decimals, the power10 used for the 32 constant is the displayPrec only when dispPrec > protocolPrec,  If less, use procolPrec.   To test this, use the one with procolPrec = 1, and adjust the diplay prec to be lower and greater.



Tools LUA:
[tempC2F-test.zip](https://github.com/user-attachments/files/18803518/tempC2F-test.zip)

![Image](https://github.com/user-attachments/assets/a57947e3-bd20-49e3-aa8d-0857396c9aa9)

![Image](https://github.com/user-attachments/assets/6fb234be-5a94-47ac-9312-3aeff4f52c24)

![Image](https://github.com/user-attachments/assets/b9954532-a605-456c-8403-039f4d742047)

**Comment by bsongis** [comment]
It has been fixed this morning, it will be in the NEXT nightlies!

**Comment by frankiearzu** [comment]
Looks good now. Will test with the real ESC telemetry tomorrow.

![Image](https://github.com/user-attachments/assets/5b55ad42-da7b-4a38-ac96-ba9027ebdf37)

**Comment by i3dm** [comment]
![Image](https://github.com/user-attachments/assets/121919e9-1378-471c-b1bd-5e1679b17c05)

I belueve there was a new bug introduced in 1.6.2 possibly while fixing this one.
Temp 1 sensor max value is now limited to 110 degrees C. Should be 1100 degrees C to support Turbine engines or other devices requiring higher temperatures.

**Comment by bsongis-frsky** [comment]
i3dm is right, I have made a mistake, I thought that the 1100°C was a typo ...
