### ISSUE TITLE
FBUS telemetry restrictions

### ISSUE THREAD

**Issue by Satcomix** [FrSkyRC/ETHOS-Feedback-Community#5202]
Hello Bertrand,
Today I did several FBUS tests with my X20S and X20Pro transmitter and receivers. With S.PORT i have no problems, only FBUS limitation.
ArcherPlus R12+ ok
Archer R6mini ok
TD-R18 ok
TD-R10 ok
TD-R6 and TD MX Limit the number of telemetry sensors to approx. 15
If more sensors are available on TD-R6 and TD-MX, only those from the receiver are displayed.
With all other receivers I was able to receive up to 45 sensors without any problems.
ETHOS 1.6.1 and 1.6.2
TD-ISRM FW3.0.1
All receivers on FW 3.0.1
best regards,
Torsten

**Comment by bsongis** [comment]
Fixed?

**Comment by Satcomix** [comment]
> Fixed?

Hello Bertrand,
No, the problem with the TD-R6 and TD-MX with the FBUS and the telemetry sensors still persists. Since no one has reported back here in the last few days, I've closed the issue.
I ran a few more tests, but the result is the same. It seems to be related to the M10 GPS and the GY-86 gyro/vario. If I remove one of these modules, everything works as expected in the FBUS protocol. There are no problems with S.PORT, works fine.
Another thing worth mentioning is that the SBUS 16CH portion of the FBUS works flawlessly. All 16CH are displayed correctly.
At first, I suspected the Temp.1 and Temp.2 sensors, like Udo (STRGALTDEL), but they're not the culprit. I bought two new receivers from Andreas Engel., the Archer Plus R6 and Archer Plus R10+. These work perfectly with older RF firmware and now also with the latest 3.0.1. firmware and the S.PORT and FBUS with 45 Telemetry-Sensors.
**Should I reopen the issue, or will you do it?**
Best regards,
Torsten

**Comment by bsongis** [comment]
I think you have to open it in the RF repository

**Comment by Satcomix** [comment]
Ok, thank you. I will go to RF.
best regards,
Torsten
