### ISSUE TITLE
Stabilizer config > 6-axis calibration

### ISSUE THREAD

**Issue by ReadyG** [FrSkyRC/ETHOS-Feedback-Community#5441]
The wording and picture of last two steps of the Stabilizer config > 6-axis calibration for the Archer SR10+ is incorrect. The wizard says to place the receiver on it's side with the label text right-side-up but it won't let you proceed unless you place the receiver on it's side with the label text upside-down. Then it tells you to place the label text upside-down but it won't let  you proceed until you place the label text right-side-up. Also, the picture shows the label text in a different orientation (180 degrees) than on the actual receiver.

**Comment by mawzthefinn** [comment]
Which script version?

**Comment by ReadyG** [comment]
Stabilizer config Script version 3.0.6

**Comment by mawzthefinn** [comment]
3.0.7 should be available in Lua Library and has some fixes around these issues

**Comment by ReadyG** [comment]
Thank you for the suggestion. I will install it, test it, and report back.

**Comment by philippe-warnotte** [comment]
The bug where points 5 and 6 are inverted is indeed fixed in version 3.0.7.
The different bitmaps depending on the receivers is a great step forward. 
Except that you forgot the TWIN series receivers! 
Example: The TW-SR10 does not look like the Archer-SR10 at all! 
No Frsky receiver looks like the TW-SR10 so this bitmap should be added. 
Some translations in different languages ​​are missing. Ex: French.

**Comment by Nicholas-Luoyi** [comment]
A new set of bitmaps for TW-SR10 will be added

**Comment by philippe-warnotte** [comment]
Perfect Nicholas !

**Comment by mawzthefinn** [comment]
CLosing off as this has been addressed

**Comment by philippe-warnotte** [comment]
This was promised by Nicholas but not resolved! lua stabilizerconfig 3.0.7 Ethos 1.6.4 nighlies: Rx tw-Sr10 still references tw-sr8 bitmap. No new bitmaps for the moment

**Comment by mawzthefinn** [comment]
The bitmaps should be in StabilizerConfig 3.0.8, they're packed in there not in the base ETHOS install.

3.0.8 is not released yet.

**Comment by philippe-warnotte** [comment]
I know that this Lua is not packaged in Ethos but if you look at the source code of Ethos 1.6.4 nightlies, you don't see any fixed Lua. That's why I allowed myself to say that it was promised but not resolved.

**Comment by mawzthefinn** [comment]
> I know that this Lua is not packaged in Ethos but if you look at the source code of Ethos 1.6.4 nightlies, you don't see any fixed Lua. That's why I allowed myself to say that it was promised but not resolved.

The StabilizerConfig Lua is published separately via the Lua Library. It's not even published in the Nightlies at all.
