### ISSUE TITLE
1.7.0 Nightly - Models from 1.6.3 invalid after model change

### ISSUE THREAD

**Issue by yak55** [FrSkyRC/ETHOS-Feedback-Community#5589]
When I open a model from 1.6.3 in the Nightly version for the first time, it works.
After the first call and a model change, it can no longer be opened.
The error message is: Data invalid.
This affects all models available in 1.6.3!

Newly created models in 1.7.0 work correctly even after a model change.

Attached is a model file

Error occurs on both the simulator and the remote control.
Tested with the following 3 transmitter variants:
X20S
X20PRO
XE

Sample models originate from an X20S.

Best regards, Eugen

[models (2).zip](https://github.com/user-attachments/files/22309337/models.2.zip)

**Comment by Wolepo** [comment]
Hello,
I added the model to Sim 1.7.0 of the X20RS. The first time I was able to open the model, but the second time I couldn't. Cloning or moving it to another folder didn't work either. There was no response whatsoever.
My own models are from 1.6.4 Nightlies after 1.7.0 and work without any problems.

**Comment by yak55** [comment]
Hello Wolfgang, that's why I created this issue and also added the model files.
I'm probably using some applications that are converted incorrectly.
When I use the same models in 1.6.4, everything works as it should.
So the error is caused by 1.7.

I'm hoping Bertrand can help.

Have a nice weekend. Eugen

**Comment by lthole** [comment]
I am having the same issue with a 1.6.3 model sent to me by @Wolepo. Can open it once, and then on the second load get a 'Model data error - invalid data.'

[sunny bird.bin.zip](https://github.com/user-attachments/files/22329434/sunny.bird.bin.zip)

**Comment by bsongis-frsky** [comment]
There are a lot of models, all fail? Which one will fail for sure?

<img width="878" height="431" alt="Image" src="https://github.com/user-attachments/assets/b64ce65e-3e59-400a-80a8-c5df10a413ed" />

**Comment by bsongis-frsky** [comment]
Reproduced with Sunny Bird from @lthole

**Comment by yak55** [comment]
Hello Bertrand, yes, all models fail. Opening only once possible. Second try data wrong. 

Eugen

**Comment by bsongis-frsky** [comment]
The Logic Swithc 44 is impossible to edit!

**Comment by Wolepo** [comment]
Why not? What's wrong with that?

![Image](https://github.com/user-attachments/assets/02583d98-cbf8-40d5-83ea-c0dba7c76f76)

**Comment by yak55** [comment]
Hello Bertrand, I have checked this.
A whole series of logic switches cannot be edited on any of the models.
However, this all works without any problems in 1.6.3.
The Simulator crashet.

Regards, Eugen

**Comment by bsongis-frsky** [comment]
Fixed in the next nightlies

**Comment by yak55** [comment]
Hello Bertrand,

I just tested the models with the XE.
I can open all logical switches.
The formatting of the switch names is now correct.

BUT: I still get an INVALID DATA ERROR when I open the model for the second time.

Best regards, Eugen

<img width="1912" height="1080" alt="Image" src="https://github.com/user-attachments/assets/cc02fa88-0fb1-4a28-a73c-96226bfc11e5" />

**Comment by bsongis-frsky** [comment]
Thanks again @yak55 for your continuous help at making Ethos better and reliable!

**Comment by yak55** [comment]
Hello Bertrand,
Just tested it with the new simulator.
It now works as desired.


Thanks 
Regards, Eugen

<img width="1920" height="1020" alt="Image" src="https://github.com/user-attachments/assets/88de63ff-8d79-4630-9dda-559e7a1b7eb6" />

**Comment by bsongis** [comment]
There is still a problem when you edit the LS75: you cannot move the cursor before the first char ...

**Comment by bsongis-frsky** [comment]
The problem should be fixed now in 1.7.0 nightlies.
The cursor shifted by 1px at each char in the TextEdit and your names are not short!
