### ISSUE TITLE
EDGE Function in Logical Switches has no INSTANT option

### ISSUE THREAD

**Issue by Hartinger** [FrSkyRC/ETHOS-Feedback-Community#89]
In ETHOS the Logical Switches include the EDGE function, as per OpenTX.
What I am missing (or have not found) is the option to specify a minimum duration, after which the LS becomes TRUE immediately.
E.g. in the following OpenTX example the LS would become TRUE as soon as SH had been held down for 1 second.

![edge](https://user-images.githubusercontent.com/22352021/115030766-bf4b5d80-9ec7-11eb-8ba4-29a906f3cfb0.PNG)

**Comment by bsongis-frsky** [comment]
Fixed in the same time than #338

**Comment by Hartinger** [comment]
I have loaded 1.0.8 onto my X10S Express.
I still cannot specify an EDGE type LS that becomes TRUE **immediately** after the specified minimum trigger duration has elapsed. I can leave the field for the maximum duration blank, however, the LS would only become TRUE after the minimum trigger duration has elapsed **and the triggering switch (momentary switch) has subsequently been released again**.
If a momentary switch is to be used for different purposes, depending on the duration of its operation, then it is essential that the function triggered by a long press is enacted instananeously after the minimum duration has elapsed. Otherwise, the behaviour would be totally confusing. (See above OpenTX example)
Please apologise if the feature is there and I just have not found it.

**Comment by bsongis-frsky** [comment]
Please check the recent 1.0.9 candidate, I have fixed a bug yesterday evening

**Comment by Hartinger** [comment]
Hi Bertrand,
I have just checked with 1.0.9 RC1 and it now works.
Thanks a lot.
