### ISSUE TITLE
model file loading error

### ISSUE THREAD

**Issue by jufelap** [FrSkyRC/ETHOS-Feedback-Community#993]
Finally there is a F3K flying configuration ready for TANDEMRE.
I downloaded it and copied it to the radio.
It starts up fine, everything works, but when I turn off the radio:

"Error message: Error opening file.
Satrting model wizard"

If I step through the wizard, it sees again all the planes I have made so far and no such error with my own creations, only with this file.
If I select the reload the model it loads nicely and starts.
But on restart the error occurs again.
I also spoke to the builder, he said several people have had the same message.
He cannot reproduce it on his device, everything is fine on his. The error is also incomprehensible to him.
One person fixed it with a re-download and paste, another person fixed it with the 1.0.11 update.

I have the radio (X20S) running EU version 1.0.11 as soon as it was released.
I don't understand what could be wrong with the file?
Everything could be set, I configured the model, but Error opening file when turning on the radio.
After selecting the wizard it works with the supposedly incorrect file.
Can anyone help me with this?
What should I do to get rid of the error?

File creator: [https://www.youtube.com/watch?v=USNN0d6yIaQ]

Download location: ArmSoar DLG Template v1.00 (Push Up For Flaps): 
[https://bit.ly/asdlgv100up]

https://bit.ly/asdlgv100
[AS_DLG_V1.00_DOWN.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7221150/AS_DLG_V1.00_DOWN.zip)
up

**Comment by mmasch** [comment]
I can also confirm this. X20S Ethos 1.0.11 EU.

**Comment by johnjoeallen** [comment]
I have an existing model I had programmed and working fine now doing this. Model loads fine once selected
[APEdgeGas.zip](https://github.com/FrSkyRC/ETHOS-Feedback-Community/files/7273267/APEdgeGas.zip)
.

**Comment by johnjoeallen** [comment]
fixed.
disk checked (Linux), unset dirty bit and fixed file system
next start got the error, changed models and back to the problem model, power off/on all ok

**Comment by BB445** [comment]
I am having the same issue as jufelap.  Running 1.011 FCC version.  Downloaded and installed the Armsoar F3K Tandem template.   

When turning on TX get the message below.  After I set up a model, switch to another model, or switch to the Armsoar template model will load just fine.  However, when I turn the radio off then and turn back on, I get the same error message.

"Error message: Error opening file.
Starting model wizard"

**Comment by BB445** [comment]
Ditto what jufelap said:   Downloaded and installed 1.012 Candidate 1 update.  Issue still exists where when you select either of Thomas Lee's (Armsoar) DLG templates as your default model and cycle the TX on and off, you will get the "error open file...starting model wizard error".   Wondering if there is some character limit on the .bin file name?  Maybe Thomas can shorten the file name?

**Comment by jufelap** [comment]
> A jufelap mondása szerint: Letöltött és telepített 1.012 Candidate 1 frissítést. A probléma továbbra is fennáll, amikor Thomas Lee (Armsoar) DLG -sablonjainak valamelyikét választja alapértelmezett modellnek, és be- és kikapcsolja a TX -et, akkor megjelenik a "hibaüzenet megnyitása ... a modell varázsló indításakor hiba". Kíváncsi vagy, hogy van -e bizonyos karakterkorlát a .bin fájlnévben? Talán Thomas le tudja rövidíteni a fájl nevét?

I have modified everything. But I couldn't find any errors anywhere.
I shortened the number of characters in all existing places to much shorter than the allowed amount. The error persists in the same way.
Maybe I missed something? 
I'll try to build it from scratch and watch when the error occurs, but I don't have the time and I don't feel like it now, I've spent so much time on it.
I have a much more serious problem, namely low range, incomprehensible RSSI signal losses. My confidence in both the ETOS and the X20S transmitter has been shaken.

**Comment by bsongis-frsky** [comment]
Would you please paste here the model from Armsoar?

**Comment by johnjoeallen** [comment]
I think ethos needs to check the dirty bit in the sd-card file system and issue a warning to fix it
